# Algorytmy populacyjne

Partially Mapped Crossover (PMX)

In [4]:
import numpy as np

In [5]:
P1 = np.array([3,4,8,2,7,1,6,5], dtype=int)
P2 = np.array([4,2,5,1,6,8,3,7], dtype=int)
O1 = np.zeros(8, dtype=int)
O2 = np.zeros(8, dtype=int)

In [7]:
cut_points = [3, 6] # after those bits
O1[cut_points[0]:cut_points[1]] = P2[cut_points[0]:cut_points[1]]
O2[cut_points[0]:cut_points[1]] = P1[cut_points[0]:cut_points[1]]
print(O1)
print(O2)


[0 0 0 1 6 8 0 0]
[0 0 0 2 7 1 0 0]


In [8]:
'''
na O1[i] - powinno być 8, ale 8 już jest na miejscu j, wtedy
-> sprawdzamy co jest na miejscu x = P2[j], jeśli x nie ma w O1 to dodajemy je na miejsce O[i], jeśli jest na miejscu z, to wtedy:
-> sprawdzamy co jest na miejscu x = P2[z], jesli x ...
'''
def func(P, O, numb):
    if numb in O:
        j = 0
        while O[j] != numb:
            j += 1
        numb = func(P, O, P[j])
    return numb

In [10]:
def myfunc(P, O, cut_points):
    return O

def filling(P,O,cut_points):
    for i in range(cut_points[0]):
        if P[i] not in O:
            O[i] = P[i]

    for i in range(len(P1) - cut_points[1]):
        if P[i+cut_points[1]] not in O:
            O[i+cut_points[1]] = P[i+cut_points[1]]

    return O

def mapping(P,O,cut_points):
    for i in range(cut_points[0]):
        if P[i] in O and P[i] != O[i]:
            j = 0
            while O[j] != P[i]:
                j += 1
            O[i] = func(P, O, P[i])
    
    for i in range(cut_points[1], len(P1)):
        if P[i] in O and P[i] != O[i]:
            j = 0
            while O[j] != P[i]:
                j += 1
            O[i] = func(P, O, P[i])

    return O

O1 = myfunc(P1,O1,cut_points)
O2 = myfunc(P2,O2,cut_points)
print(" ", O1,"\n ",O2)

  [3 4 2 1 6 8 7 5] 
  [4 8 5 2 7 1 3 6]


In [1]:
for i in range(2,7):
    print(i)

2
3
4
5
6
